### ISSUE TITLE
Subcircuits with RAM share RAM state

### ISSUE THREAD

**Issue by carlor** [reds-heig/logisim-evolution#100]
Let's say you have a circuit `main`, and a circuit `subcircuit` which has RAM inside it.

If `main` has two `subcircuit`s inside it, though e.g. registers in the `subcircuit`s can have separate values, if one `subcircuit` writes to RAM, the value will appear in the other RAM. I don't think that's intended.

I've attached an example.
[ram_bug.zip](https://github.com/reds-heig/logisim-evolution/files/659576/ram_bug.zip)

**Comment by BFH-ktt1** [comment]
Dear Carlor,
Sorry for replying so late! You are right, the ram has a serious flaw. I tracked down the problem which is related to the Attribute Ram.CONTENTS_ATTR; in the implementation of the RAM's all which have the same other attributes share this particular attribute which contains the RAM-contents. Cloning this attribute will solve the problem; however, it will break the ability to change the RAM-contents by the attribute editor. I'm investigating further in this issue as I am currently implementing the possibility that all memory components start with an "unknown" state as in real circuits. Please stay tuned and keep an eye on the current scaling-wip branch on which I'm working.

**Comment by BFH-ktt1** [comment]
My latest push in the scaling-resolution wip fixes the problem, please give it a try
