### ISSUE TITLE
BUG: Adding new pins rotating labels + subcircuit rotation 

### ISSUE THREAD

**Issue by BFH-ktt1** [reds-heig/logisim-evolution#105]
There is an issue introduced by this nice feature:
If I have modified slightly the appearance of the sub-circuit, the labels etc. will show up duplicated (see attached logisim circuit).

[example.zip](https://github.com/reds-heig/logisim-evolution/files/785798/example.zip)

**Comment by alexandremalki** [comment]
Hi Theo,
I reverted this commit. You can pull the last commit. Thank you for your feedback. I am going to work on solving the issue on the next release.

**Comment by BFH-ktt1** [comment]
Hi Alexandre,
Unfortunately the revert broke completely the copy-past feature of logisim. When selecting a block, performing a copy, and than a paste will only paste the wires. All components are lost in the pasted block.

**Comment by alexandremalki** [comment]
This is correct in the newest comit.

**Comment by BFH-ktt1** [comment]
Super, Thanks!
