### ISSUE TITLE
Pop up at close

### ISSUE THREAD

**Issue by Leumass96** [reds-heig/logisim-evolution#106]
First of all your job to make Logisim compatible with high resolution display is really impressive. I had this problem with my laptop and had to change the resolution settings and reboot before using Logisim. Also thank you ! 
I just saw that the pop up which is asking if you want to save your job before closing the program is not scaled yet. I think you always know that and it is obviously not so relevant. 
Thanks again for your job
Samuel

**Comment by BFH-ktt1** [comment]
Dear Samuel,
The scaling-wip branch now should scale everything. Please give it a try.
