### ISSUE TITLE
Combinatorial analysis missing

### ISSUE THREAD

**Issue by Leumass96** [reds-heig/logisim-evolution#111]
In the experimental version 2.13.23, the combinatorial analysis is missing. This functionality is very useful so it is a big loss.

Thanks

**Comment by maehne** [comment]
The combinatorial analysis is always deactivated by default due to didactic reasons. It can be enabled by launching logisim-evolution.jar with the -analyze option. The default can be set via the static member variable ANALYZE in the Main class.

**Comment by BFH-ktt1** [comment]
You can now also build with ant jar_all which will generate a jar with the analyzer enabled and the documentation included.

**Comment by Leumass96** [comment]
I am sorry but I can't find how to export correctly the java project into a jar file which I can run. Can you help me ?

**Comment by leadrien** [comment]
You need to use apache ant command.
In the project root directory run: 
`ant jar`
It will produce a logisim-evolution.jar file

**Comment by maehne** [comment]
If you are compiling from the ```scaling_resolution_wip``` branch with the most recent changes, you may also try in addition ```ant package```, which will generate an OS-specific installer with logisim-evolution properly wrapped into an executable, which facilitates associating the ```.circ``` file extension for opening up in logisim-evolution.

**Comment by Leumass96** [comment]
Thank you very much for your help ! I did it and I didn't know ant. It is very useful.
Thanks

**Comment by jessetheasian** [comment]
If anyone is having trouble enabling the 'analysis circuit' tool I found a tutorial: https://www.youtube.com/watch?v=9p2uBG9RLqU
