### ISSUE TITLE
Zooming behavior is strange

### ISSUE THREAD

**Issue by janissimsons** [reds-heig/logisim-evolution#130]
Hi,

It seems possible only to zoom into upper-left corner and then pan the project with arrows, which is kind of awkward and strange.
Could you please implement zooming into any region of the project and add some sort of panning capability, so we can easier navigate the project.

Thank you

**Comment by LordDecapo** [comment]
I second this panning feature

**Comment by BFH-ktt1** [comment]
This sound like a great feature, please implement it and send us a merge request.

**Comment by LogisimIt** [comment]
I did it a few months ago in my fork, if you want, just copy it

**Comment by BFH-ktt1** [comment]
Could you please submit a pull-request on these changes such that I can merge it into the testing branch?
Thanks for the work!

**Comment by BFH-ktt1** [comment]
New zoom behavior based on the logisim-ita branch has been implemented in the scaling_resolution_wip branch, hence closing this issue,
