### ISSUE TITLE
Java 9 issue

### ISSUE THREAD

**Issue by b1u3-YumaNoguchi** [reds-heig/logisim-evolution#133]
Hi!

I found a issue about java9.
When logisim-evolution run with java 9, it doesn't work.
The cause is net.roydesign.mac.MRJAdapter.java in mrjadapter.jar.

Then I got code from [krichter722/arjadapter](https://github.com/krichter722/mrjadapter/tree/master/mrjadapter/src/main/java/net/roydesign)
and changed net.roydesign.mac.MRJAdapter.java

from

>javaVersion = new Float(prop.substring(0, 3)).floatValue();

to 

> if(Integer.valueOf(String.valueOf(prop.charAt(0)))>=9){
>                 javaVersion = new Float(prop);
>         }else{
>                 javaVersion = new Float(prop.substring(0, 3)).floatValue();
> }

I compiled it and built logisim-evolution. It ran well.
But this is my first issue. Is this right? And How can I do?

**Comment by marvk** [comment]
This [issue exists already](https://github.com/reds-heig/logisim-evolution/issues/131), but has been (apparently) wrongly closed:

**Comment by b1u3-YumaNoguchi** [comment]
Oh,  you reopened that issue. I haven't noticed that. Should I close this issue(#133)?

**Comment by alexandremalki** [comment]
This is done. You can continue on the ticket #131
