### ISSUE TITLE
FPGA Commander: Don't use the user's home directory as the default workspace directory

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#144]
Currently, the FPGA Commander pollutes by default the user's home directory with its temporary files. This can be changed by choosing an appropriate directory as the Workspace in the FPGA Commander window. It would be nice if the workspace would be set to a sensible default value, e.g., ```~/logisim_workspace``` or ```~/.logisim/workspace```.

**Comment by BFH-ktt1** [comment]
Changed in the latest push on the scaling_resolution_wip
