### ISSUE TITLE
Run assemble program

### ISSUE THREAD

**Issue by Kiddinglife** [reds-heig/logisim-evolution#149]
If I draw a mips cpu using logic-evolution, then how to run my assemble program on it?
I think there is a way to transfer my asm codes to the ram? Am I right?

**Comment by alexandremalki** [comment]
You shall use the Rom component where you can load an image. We made ARM cpu and use ROM for data.
The first line has to be v2.0 raw then the file can be completed with hexadecimal data corresponding to your code. This is one example for 16bits data memory ROM:
```bash
v2.0 raw                
 #Commentary line      
e002 0000 0000 0000 2201 2303 189a 3b01             
d1fc 46c0 46c0 46c0 46c0 46c0

**Comment by Kiddinglife** [comment]
Thank you! I can close this issues now.
