### ISSUE TITLE
Compare logicsim-evolution with Digital

### ISSUE THREAD

**Issue by Kiddinglife** [reds-heig/logisim-evolution#150]
Hi mate,
I am comparing logicsim-evolution with Digital https://github.com/hneemann/Digital.

Digital is to solve out 3 major problems that exist in logicsim and they are highlighted below:
>**Switching On**
In Logisim there is no real "switching on" of a circuit. The simulation is running also while you are modifying it. This causes sometimes an unexpected behaviour. So its possible to build a simple master-slave flip-flop which works fine. But after a circuit reset the flip-flop does not work anymore.

>**Embedded circuits**
Similar to Logisim, Digital also allows to embed previously saved circuits in new designs, so hierarchical circuits can be created. However, in Digital embedded circuits are included as often as the circuit is used.

>**Oscillations**
With Logisim it is hard to find the root cause for oscillating circuits. If Logisim detects an oscillation, a corresponding message is issued, but it is not possible to investigate the cause in more detail, so it is difficult to understand what happens.

I went though all the commits of logic-evolution and did not found anything related to fix up of those issues.So, can you tell me if those issues are encountered or solved out in logic-evolution?

Thanks,
Jacky.

**Comment by alexandremalki** [comment]
Hi Kiddinglife,
I am going to walk trought the issues you raised:
* **Switching on** : currently there is not circuit switching on and off.
* **Embedded circuits** : such a feature is possible. Under logisim this is call a library.
*  **Oscillation** : From what I recall, logisim does not indicate you the cause of the issue.

Have a nice day.

**Comment by Kiddinglife** [comment]
thanks i will close this issue ticket.
