### ISSUE TITLE
Additional components request.

### ISSUE THREAD

**Issue by Nightquaker** [reds-heig/logisim-evolution#157]
Hello there!
It would be quite nice if certain components from Logisim-ITA were integrated.
For example, the switches (normal ones, not dip switches) and digital oscilloscope.
And, if at all possible, the TTL library.

**Comment by BFH-ktt1** [comment]
I contacted the developers of Logisim-ITA and await their respons.

**Comment by BFH-ktt1** [comment]
The TTL-library of logisim-ITA has been merged into the scaling_resolution_wip. After my holidays I hope to continue merging the very nice features of logisim-ITA.

**Comment by BFH-ktt1** [comment]
I have merged all logisim-ITA components like switches oscilloscope PLA-rom, etc. in a special lbuild-in library called logisim-ITA components in the scaling_resolution_wip branch. With this I close this issue; have fun and thanks a lot to the logisim-ITA crew!
