### ISSUE TITLE
Carryout bits of multiply have incorrect sign

### ISSUE THREAD

**Issue by sruthiveeragandham** [reds-heig/logisim-evolution#168]
Maybe this is just how the multiply block is intended to work, but something we noticed when using the multiply block is that the carryout bits don't get sign-extended when there are less carryout bits than output bits. For example for 0x0000FFFF (-65536) * 0x0FFFFFFF (+268435455), the output is 0xFFFEFFF00010000, which is only 60 bits. When you connect a 32-bit output to the carryout pin, you get 0x0FFFEFFF; if you combine this 32 bit output with the lower 32 bits, the result treated as a 64-bit 2's complement number is not correct. I would expect the result to actually be 0xFFFFF000, which is what the upper bits would be if the multiplication was signed. 0x0FFFEFFF are the correct upper bits from the unsigned multiplication.

![image](https://user-images.githubusercontent.com/25261983/42851135-d9a22736-89df-11e8-8885-9976f4413aaa.png)

**Comment by YulienPohl** [comment]
The multiplier is intended to be an unsigned component.
Before Update v2.14.5 the multiplier had only 31 bit because of the wrong sign extension.
