### ISSUE TITLE
Cannot load file from command line

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#169]
In previous versions it was possible to load a .circ file directly from command line simply by specifying its path after the Logisim-Evolution's jar file (i.e., _java -jar logisim-evolution.jar <filepath>_). This is no longer possible in v2.14.6 since the file path is interpreted as a simulator name and the software returns the error
`[main] ERROR com.cburch.logisim.gui.start.Startup - FATAL ERROR - no simulator available`

This is pretty annoying, especially since it forbids one from loading files from a GUI (without passing from _File->Open_).

The previous behaviour should therefore be restored.

**Comment by BFH-ktt1** [comment]
fixed in the last push
