### ISSUE TITLE
"Sensible names" in Logisim

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#17]
There are some words that are forbidden in Logisim: if they are used, weird errors appear when downloading on the board.
It would be nice to identify these names (for instance, "top_sim"), understand why this happens, and solve the problem (either by displaying an error when they are used, or by solving the problem preventing their use).

**Comment by BFH-ktt1** [comment]
Should be realized by my latest push

**Comment by reds-heig** [comment]
Hi,

Thanks a lot for your patches! :)
I'll integrate the changes in the tracked version, doing a release 
during the pause in the student's holidays (around the beginning of 
February).
Best,
Rob

On 01/18/2016 08:22 PM, Prof. Dr. Theo Kluter wrote:
> Closed #17 <https://github.com/reds-heig/logisim-evolution/issues/17>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reds-heig/logisim-evolution/issues/17#event-518285478>.
>

-- 
==========================================================
Roberto Rigamonti - Ph.D EPFL
R&D Engineer

Institut Reconfigurable & Embedded Digital Systems (REDS)

Haute École d'Ingénierie et de Gestion du Canton de Vaud
Route de Cheseaux 1 - CP 521 - 1401 Yverdon-les-Bains (CH)
==========================================================
