### ISSUE TITLE
Update of LPG in v3

### ISSUE THREAD

**Issue by mbaillif** [reds-heig/logisim-evolution#172]
In the fork mbaillif branch test
I updated the text of the GPL (gpl.html) in its version V3 in accordance with the conventions
I also modify the text (fr / en ) of about (index.html) to match the recent description.
Can you check if this fits the idea of the project?
before going further

**Comment by BFH-ktt1** [comment]
Dear mbaillif,
Thanks for the work, I will look soon into your modifs

**Comment by mbaillif** [comment]
The most successful version of the translation is in the branch
mbaillif / logisim-evolution master.

Everything has been written to fit the sun javahelp library.
There is still work but the doc fr is presentable.

The guide section is almost complete, the test vectors page, and the fpga related parts are still missing.

I already have the figures for the English version.

**Comment by BFH-ktt1** [comment]
I am not sure if with the latest pull requests we integrated all. Are there open tasks or can we close this issue?

**Comment by mbaillif** [comment]
Everything is in order, can be closed
