### ISSUE TITLE
Circuit Randomly Breaks

### ISSUE THREAD

**Issue by SpaceboyRoss01** [reds-heig/logisim-evolution#179]
I'm building a CPU and when I had placed the CPU circuit onto the motherboard circuit, the CPU showed a red outline. I checked the other files and my CPU shows a red outline around the 16-Bit ALU, then I checked the 16-Bit ALU and the 1-Bit ALU's have a red outline. I don't know what's going on and how to fix it.

# 1-Bit ALU
![screenshot from 2018-10-05 12-41-08](https://user-images.githubusercontent.com/19699320/46556588-f292e780-c89b-11e8-83e5-b4f5c3d3e2e9.png)

# 16-Bit ALU 
![screenshot from 2018-10-05 12-40-44](https://user-images.githubusercontent.com/19699320/46556564-e444cb80-c89b-11e8-8f45-a1c8f30e2986.png)

# CPU
![screenshot from 2018-10-05 12-40-13](https://user-images.githubusercontent.com/19699320/46556537-d131fb80-c89b-11e8-8316-7be8361d8e07.png)

# Motherboard
![screenshot from 2018-10-05 12-41-32](https://user-images.githubusercontent.com/19699320/46556615-00486d00-c89c-11e8-8a94-172f33d4c113.png)

**Comment by BFH-ktt1** [comment]
You have a combinational loop in your carry-chain that causes oscillation. You should put somewhere in your carry-chain a flipflop to break this oscillation.

**Comment by BFH-ktt1** [comment]
In addition you have a short-circuit in the input less and the output of the adder cout. This will also cause in certain conditions a problem.
