### ISSUE TITLE
Include the possibility to add a new board without recompiling

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#18]
At present if a new card is added, before being able to see it in the list of available boards, one has to recompile and produce a new Logisim version. Ideally, this shouldn't be the case and the board should be immediately available.

**Comment by BFH-ktt1** [comment]
This is already four years of my stack of TODO's. In principle there is already a menu item, it's just that the back-end fails :-< I planed for it already in the past, and hope I'll find some time in the near future to implement it, as I have seen that this would be a great improvement of flexibility. To add to this list might be the possibility to "hide" existing boards from the list or even remove them without the requirement to recompile.

**Comment by BFH-ktt1** [comment]
I added 90% of this feature in my latest push. The only part that is left is to have the ability to remove external boards from the FPGA commander.

**Comment by reds-heig** [comment]
Great, thanks!!

**Comment by BFH-ktt1** [comment]
Completely implemented by my last push. Closing the issue.
