### ISSUE TITLE
Command line option -test does not seem to work on 2.14.6

### ISSUE THREAD

**Issue by eencae** [reds-heig/logisim-evolution#185]
I use the command line option -test to automatically grade student solutions (pass in their file, circuit name and a test vector). This worked fine on 2.14.2, but no longer appears to work on the latest version (2.1.4.6).

**Comment by mbaillif** [comment]
l'option -test a été remplacé par -testvector in 2.14.6

**Comment by BFH-ktt1** [comment]
Can this issue be closed?

**Comment by BFH-ktt1** [comment]
Due to long inactivity closing the issue.
