### ISSUE TITLE
V2.14.7  The outputs no longer show in color their state

### ISSUE THREAD

**Issue by mbaillif** [reds-heig/logisim-evolution#186]
A small note on the components "pin" The outputs no longer show in color their state.
This will be an advantage if these representations keep the same width as two squares (in 1 bit wide) in north-south orientation (reverse compatibility).

**Comment by mbaillif** [comment]
Precision
![image](https://user-images.githubusercontent.com/42096681/49248848-f7e35d00-f41a-11e8-8fde-d64e1f3273d3.png)

**Comment by BFH-ktt1** [comment]
Please take a look at the latest version. The sizes have been fixed for the single bit. My action plan is to move even further and keep the size of the input-symbols equal in each direction by rotation the bit-vectors in case of north and south orientation. As soon as I have this realized I will post a comment.

**Comment by BFH-ktt1** [comment]
This should be fixed in the latest version, closing the issue, please feel free to reopen if you think there is still an issue.
