### ISSUE TITLE
Show bases on IO

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#22]
When printing schemes, the bases of I/O are not shown.
It would be nice to have a small symbol indicating
- b for binary
- o for octal
- u for unsigned decimal
- s for signed decimal
- h for hex

The image below shows why this could avoid headaches in certain cases...
![radix_logisim](https://cloud.githubusercontent.com/assets/8828893/7344341/f57b198c-ecca-11e4-93de-ad681a4afbb1.png)

**Comment by BFH-ktt1** [comment]
pushed in my last change, closing
