### ISSUE TITLE
Random Generator Oscillates

### ISSUE THREAD

**Issue by LordDecapo** [reds-heig/logisim-evolution#229]
I have found that when you have the following conditions, a Random Generator will Oscillate. 
Reset - 1
Enable - X
Clock - X
![image](https://user-images.githubusercontent.com/20075869/53217143-f0e87700-3624-11e9-85ea-6fb88f2293c6.png)

[Dropbox link for a circ](https://www.dropbox.com/s/o5c2u7okmz1pfmf/RNG_Issue.circ?dl=0)

Used Logisim v2.15.0 on Windows 10.

**Comment by BFH-ktt1** [comment]
@LordDecapo : This is for me a known issue and on the list to be fixed. For the time being the problem can be solved by putting for the attribute "seed" a number different than "0". Hope this helps for the time being, I will try to find a fix asap.

**Comment by BFH-ktt1** [comment]
Fixed with my latest pull request.
