### ISSUE TITLE
Suppress the confusion between "Pin in" and "Pin out"

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#23]
People often have problems because they forget to change the in/out type of a pin, or its orientation (or both).
To solve this issue, the multi-usage pin should be replaced by two components
- Pin_In with the connection on the right and without the property "Output?"
- Pin_Out with the connection on the left and without the property "Output?"

Also, verify that the pin components in the bar are the new ones, and that this change is retro-compatible!

**Comment by Akari1982** [comment]
Don't forget about bidirectional pins. In most cases on chip has data pins that works both way. It's very hacky to emulate this behavior by duplicate pins. Maybe it's better to remove this two behaviors and create one bidirectional pin.

**Comment by robertorigamonti** [comment]
It is a good idea, but unfortunately I think that many parts of logisim rely on the in/out dichotomy of the pins -- having inout pins would probably create weird errors :(

**Comment by BFH-ktt1** [comment]
pushed in last change, closing
