### ISSUE TITLE
Changing shifter type does not recompute output

### ISSUE THREAD

**Issue by jimbo1qaz** [reds-heig/logisim-evolution#239]
If I change the type of a shifter (arithmetic/logical/circular and direction), the output does not change.

- Adding/removing output probes does not help.
- Saving and reopening the document resets all pin inputs to 0.
- Changing the pin input causes the output to change and reflect the shifter type.

logisim-evolution 2.15.0

**Comment by BFH-ktt1** [comment]
Fixed in my latest push, thanks for the report!
