### ISSUE TITLE
Placing several components of the same components works not reliably

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#240]
Steps to reproduce:

1. Open Logisim-evolution
2. Select "AND Gate" from "Gates" and place it on the schematic. Note, the Gates library closes.∑
3. Select again "AND Gate" from "Gates" and place it on the schematic. Note, this time the Gates library remains open and "AND Gate" remains selected.
4. As long as "AND Gate" remains selected, you cannot anymore place more "AND Gates", which constitutes the bug.
5. Workaround: Select another Gate, e.g., "OR Gate", and then select again "AND Gate" to place more of them.

I observed this with Logisim-evolution built from the current development head (commit 9fb3ac8) on Debian Buster and macOS High Sierra.

**Comment by BFH-ktt1** [comment]
Fixed by the latest merge, closing
