### ISSUE TITLE
FPGA Commander: Save Map does not ensure .xml file extension

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#245]
If the user changes the file name in the Save Map dialogue of the FPGA Commander, it is not ensured that the new file name has the extension ``.xml``. Users are not used to have to enter the file extension themselves, so they are surprised to not see then there saved Map files due to the then missing file extension.

**Comment by BFH-ktt1** [comment]
In my next push the FPGA commander will add a .xml extention when not preset. this will also solve issue #246. Thanks for the report!
