### ISSUE TITLE
Add a new "Do not connect" component to the "Wiring" library

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#247]
Sometimes outputs of components or bus splitters are not connected on purpose in Logisim circuits, e.g., if only certain bits of a bus are needed of if two splitters are used to implement a shift by a fixed number of bits. This yields "Found a source with a sink" warnings in the FPGA Commander. This warning can be useful in many cases, but annoying in those cases, where it is done on purpose. Therefore, I propose to add a "Do not connect" component to the "Wiring" library, which shape could be, e.g., a red cross like it is available other schematic entry tools. The functionality of this new block should be only to silence the "Found a source without a sink" warnings.

Currently, there does not seem to be a reliable workaround to silence this kind of warning. In the case of bus splitters, I had some success by limiting the fan out of the splitter to just the needed number of in-/outputs while the bit width would be set to the size of the connected bus and the bits assigned by hand to the different outputs or to "None". However, this still yielded the warning in some cases, while implementing a "wire-only shifter". Inserting explicitly "Buffer" gates between the inputs and outputs helped in some cases and in others not. In the latter case, I finally succeeded to silence the warning by inserting additional "Buffer"s to the unused input signals and leaving their outputs open. So, there seems already some special casings for unused outputs in place. If the DRC check by the FPGA Commander could be made to work more reliably, the addition of the "Do not connect" component might become less urgent, as it would then only serve documentation purposes.

**Comment by BFH-ktt1** [comment]
Added in my latest push in my working tree, will merge with development when I finished my current tree of merging of the holy cross edition.
