### ISSUE TITLE
FPGA Commander: Load Map should issue a warning if the selected map file does not correspond to the selected top-level circuit

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#248]
The Load Map function in the pin mapping dialogue of the FPGA Commander should issue a warning if the selected map file does not correspond to the selected top-level circuit instead of silently not applying the mapping.

**Comment by BFH-ktt1** [comment]
This issue is solved by my latest pushes in develop (as the separate map file is now obsolete, the mapping is now stored in the .circ file), will close it.
