### ISSUE TITLE
FPGA Commander: Netlisting gets stuck if components get connected to splitter inputs that are set to None

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#250]
I submitted a test case "Watch_PZ_12_mht1.circ" to @BFH-ktt1 where net listing in the FPGA commander gets stuck in a sub-circuit after I tried to fix "Found a sink without a source" warnings by connecting the open inputs to ground in that sub-circuit. At this point, it is impossible to abort the net listing even though the schematic entry of Logisim is still usable. One has to kill Logisim-evolution and start again to continue the work. I then noticed in the concerned sub-circuit that the splitter inputs, which I connected to ground, had been set to "None".

**Comment by maehne** [comment]
I was able to reduce the test case (see attachment).
[netlisting_bug.zip](https://github.com/reds-heig/logisim-evolution/files/3042738/netlisting_bug.zip)

**Comment by BFH-ktt1** [comment]
Fixed in my latest push, please re-open if it doesnt solve the problem
