### ISSUE TITLE
FPGA Commander: Multiple drivers are not detected during Logisim's design rule check

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#257]
Multiple drivers connected to the same signal are not found by the DRC pass of the FPGA Commander:

![image](https://user-images.githubusercontent.com/1174243/56395772-46fc2400-623c-11e9-8c19-e1484e261927.png)

Instead, synthesis with Quartus fails in phase "Optimizing Altera project". Attached, you can find a minimal test case.

[test_multiple_drivers.zip](https://github.com/reds-heig/logisim-evolution/files/3096403/test_multiple_drivers.zip)

**Comment by BFH-ktt1** [comment]
fixed in my latest push, please reopen if the problem reappears.
