### ISSUE TITLE
FPGA Commander should check for duplicate identifiers

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#304]
Synthesis might fail in FPGA Commander with "Fatal Error found in stage Optimizing Altera Project" even if all FPGA Commander warnings have been fixed previously. The cause in the case reported by one of our students (cf. to [Moodle Forum](https://moodle.bfh.ch/mod/forum/discuss.php?d=69303)) is the use of `Carry` as name for a circuit sheet and the use of `carry` to name the output port in the same one.

Therefore, FPGA Commander should check for duplicate labels in each entity/architecture and report them as being problematic for synthesis. As far as I can see. at least the entity name, inputs/outputs as well as internal signals and names of block instances should get checked for duplicates.

**Comment by BFH-ktt1** [comment]
Should be fixed in my latest push, please reopen if the issue still persists.
