### ISSUE TITLE
Bug in version 3.2.0

### ISSUE THREAD

**Issue by mbaillif** [reds-heig/logisim-evolution#308]
If in place a free text on a schema, even just one.
There's this message when you're save the circuit.
"Text component not found."
3.2.0 from Branch develop

**Comment by BFH-ktt1** [comment]
I can reproduce, thanks for the catch!

**Comment by BFH-ktt1** [comment]
Fixed in my latest push, closing the issue, please reopen if the problem is not solved.

**Comment by micahwagner** [comment]
every time I put text down in a schematic scheme and try to save, it says "Text component not found." for every text component in the scheme. This does not happen when I put text in a circuit appearance.

**Comment by micahwagner** [comment]
I have the newest version of logisim-evolution

**Comment by micahwagner** [comment]
the version I'm talking about is 3.4.4

**Comment by micahwagner** [comment]
sorry for mentioning it again, I didn't know it was tracked already
