### ISSUE TITLE
Importing original logisim files before evolution as circuit or library does not always preserve correct appearance

### ISSUE THREAD

**Issue by BFH-ktt1** [reds-heig/logisim-evolution#334]
I discovered that when importing the TTL-circuit library as circuit the flipflop-appearance are taken as the default set in evolution (in my case logisim-evolution). This causes problems as they should have classic-logisim.
Furthermore, when importing the TTL-circuit library as library, the sub-circuit shapes are lost (the sub-circuit should retain the appearance "custom" instead of the default set in the settings (in my case logisim-evolution)).
I discovered this bug when I was looking into issue #326

**Comment by Triavanicus** [comment]
#397 and this issue are fixed by the same commit.
