### ISSUE TITLE
Rotary encoder Input?

### ISSUE THREAD

**Issue by Timshoo** [reds-heig/logisim-evolution#353]
Has anybody made a rotary encoder as an input? Like a quadrature or even multi-bit absolute.

**Comment by maehne** [comment]
You can build it yourself with reasonable effort. E.g., [Wikipedia] gives you some nice hints how to do it. This is a typical design task for introductory digital design classes, in which Logisim-evolution is primarily used.

**Comment by maehne** [comment]
@BFH-ktt1: I suggest to close this issue as "won't fix".
