### ISSUE TITLE
Wiring -- bus crossing identical to bus connection

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#36]
When two wires are connected, a blob appears to mark the connection (to avoid mistaking it for a crossing). For the buses, a blob also appears, but its size is so close to that of the bus that it is invisible.
See for instance the image -- there are 3 connections and 2 crossings.

![ticket](https://cloud.githubusercontent.com/assets/8828893/7831781/22c02788-045a-11e5-9401-4db20ebf9ab8.png)

**Comment by BFH-ktt1** [comment]
Fixed this issue in my last push There was also an issue that the size of the bus did not increase in case that the bus is highlighted. Also this issue is fixed.
