### ISSUE TITLE
Show signal names in circuit's instantiation

### ISSUE THREAD

**Issue by reds-heig** [reds-heig/logisim-evolution#37]
For the moment, when the mouse pointer passes over a circuit's pin, the signal name is shown. This is insufficient, as when the schema is printed these names are not visible.

Requested functionality: show in a circuit's symbol then names of the signals given in the schema.

**Comment by BFH-ktt1** [comment]
I changed with my latest push the appearance of circuits such that the labels of the input(s) and outputs(s) of the circuit are directly visible in the default symbol.
Furthermore, no pins will be shown on the north and south side.
Maybe it is not the nicest display of the subcircuits, but I think it is more visible. I'm open to suggestions how we could even make the default appearance better/nicer.

**Comment by reds-heig** [comment]
There seems to be a problem with the modifications: now, each time I add a component and start adding wires or pins, it creates a couple of new empty Java windows. Even changing pin's properties (like the name) seems to foster further window creation...
Could you please have a look at it?
Thanks a lot for your help! :)
![menu_bar](https://cloud.githubusercontent.com/assets/8828893/11112050/75d2a042-890f-11e5-8415-d6e8f0ba6ef5.png)

**Comment by BFH-ktt1** [comment]
Oops, forgot in my hack to dispose the windows ;-)
My latest push should fix this problem.
The small hack I had to make is that for getting the font metrics I need to have a graphics. As in the method the graphics is not know, I create a frame and a panel to get the font metrics. It is kind of a dirty hack, but works for now. Maybe it should be cleaned up later on.

**Comment by reds-heig** [comment]
It seems to work perfectly, thanks!
