### ISSUE TITLE
PLA component (Input/Output-extra library) has no description

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#380]
The PLA component in the Input/Output-extra library is lacking a description, as can be seen in this screenshot taken from Logisim-evolution built from HEAD of the develop branch (commit 5fc1a067):

<img width="274" alt="image" src="https://user-images.githubusercontent.com/1174243/78539611-22091400-77f3-11ea-84c4-4970070b9d40.png">

**Comment by BFH-ktt1** [comment]
Fixed in my latest push
