### ISSUE TITLE
Add "Reset window layout" to Window menu to recover from unusable GUI

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#381]
The Left panel and therein contained Library and Property panes can be made to disappear by resizing them using the mouse (see screenshots below). Even the main circuit drawing area can be made to disappear (see screenshot below). Unfortunately, it is not possible to make reappear the respective panel/pane, as there's no widget element allowing to resize it back to its initial size. (This is not completely true on all platforms: On Linux and Windows I was able drag back the vertical line to make reappear the left pane or the drawing area. Though, this does not seem to work at all for the design and property panes. The problem seem to be independent of the configured Look & Feel. On macOS, I am not even able to drag the vertical to make reappear the left pane or the drawing area.) 

As the Library and Property panes offer functions, which cannot be reached by other means, Logisim-evolution becomes unusable! Unfortunately, this size change gets instantly saved to the Logisim preferences so that even restarting Logisim-evolution does not help.

The only way to reset the initial window layout is to delete the Logisim settings **when all instances of Logisim-evolution are closed.** Unfortunately, they get stored in different places depending on the OS:

- In Windows the settings are stored in the registry under the key "Computer\HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\cburch".

- In macOS the settings are stored in the file "~/Library/Preferences/com.cburch.logisim.plist".

- In Linux, the settings are saved in the folder "~/.java/.userPrefs/com/cburch/".

I did not find any other way to do this through the Logisim-evolution GUI even though, I checked the program preferences, project options, Edit menu, and Window menu for appropriate options. Even the promising button "Project -> Options -> Reset -> Reset All Settings" won't help in this matter. Anyway, I would suggest adding a more easily to find way to restore the initial window layout, e.g., by adding a menu item "Reset window layout" to the Window menu.

![grafik](https://user-images.githubusercontent.com/1174243/78565848-bc328180-781e-11ea-901d-69c06af17186.png)

![grafik](https://user-images.githubusercontent.com/1174243/78565939-d8ceb980-781e-11ea-88c9-f038775d56e5.png)

![grafik](https://user-images.githubusercontent.com/1174243/78565994-eb48f300-781e-11ea-8525-ae1e72185767.png)

![grafik](https://user-images.githubusercontent.com/1174243/78566131-13d0ed00-781f-11ea-90eb-672a8223b76a.png)

**Comment by maehne** [comment]
Maybe, making these different panes to disappear could be suppressed alltogether by forcing a minimum size to each of them?

**Comment by BFH-ktt1** [comment]
The dissapear is a "wanted feature" that is used in Logisim. Hence preventing the minimal/maximal size will go against some of the features used. I added a button in the preferences -> window with which the default layout can be restored.
