### ISSUE TITLE
Severe gated clock warning when providing system clock through input pin

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#395]
In a student project involving two FPGA boards, we have one of the boards acting as master and the other as slave. The master provides to the slave the clock signal to be used for its entire design. Logisim-evolution reports the entire clock network starting from that clock input pin as a gated clock line (severe warning). The circuit works nevertheless. Anyway, it would be nice if this severe warning could be avoided, e.g., by making it possible to mark an input pin explicitly as a clock source.

As the severe gated clock warning is reported for each clock sink, it can easily drown other warnings, which hint to real problems remaining in the design.

**Comment by BFH-ktt1** [comment]
Fixed by check boxes in settings window, closing issue
