### ISSUE TITLE
Help for Chronogram?

### ISSUE THREAD

**Issue by markarmb** [reds-heig/logisim-evolution#4]
There does not appear to be any help for the Chronogram.

I build a simple circuit consisting of the system clock connected to a T flip-flop.  I add 'Clock' and 'T Flip-Flop' in the selection tab and select 'Clock' for "Choose your clock".

The Start Chronogram button brings up a Window with no display and the status message "Add 'sysclk' signal in Simulate->Chronogram for real time use, or load file"

There is no 'sysclk' available to add.

How do you make the Chronogram work?

**Comment by reds-heig** [comment]
Yes, this is the tutorial we use for the students in our labs.
Indeed, the chronogram is not that straightforward to use -- but we are rewriting it from scratch.
However, you guessed correctly, you need a clock with the label sysclk which is not linked with any component, and then define the clock clk for the circuit.
Also, the clock is steppable using the F2 key, but ONLY if the circuit that you are working on is marked as main (it should be in blue in the list).
Thanks for the suggestion, I will add the tutorial to the main page.
