### ISSUE TITLE
Logisim ITA fixed pinout of ttl7402

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#400]
Logisim ITA fixed in commit https://github.com/LogisimIt/Logisim/commit/a161d0916ef03a8747edb2a708674d8ed551baa4 the layout of ttl7402, which is also provided by Logisim-evolution. Additionally, a typo got fixed in a comment https://github.com/LogisimIt/Logisim/commit/3b263bfa00671b0c349eea4582840670cad247d7 in the static `paintDoubleInputgate` method.

**Comment by BFH-ktt1** [comment]
Added in my next push, closing issue
