### ISSUE TITLE
ROM/RAM can't have any address width other then 8.

### ISSUE THREAD

**Issue by wgaylord** [reds-heig/logisim-evolution#423]
Currently there is a bug where the actual bus width for the addressing of RAM and ROM do not change when you adjust the value in the menu on the left. The graphics update to show the new address width but the actual bus that you connect to does not change width.

Version 3.3.6 

JAVA
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

On windows 10

It appears that if you save and reload the file the bus then takes on the correct width but if you then change it again you will have to save and reload it for that change to take effect.

**Comment by BFH-ktt1** [comment]
I confirm the bug (which by the way was also true for the ROM). It has been fixed in my latest push in develop. Please reopen if this push did not fix the problem.

**Comment by wgaylord** [comment]
Okay. I will compile dev branch later today to test it out.

**Comment by wgaylord** [comment]
It works!
