### ISSUE TITLE
Triple XOR Input

### ISSUE THREAD

**Issue by Isam-Ilyas29** [reds-heig/logisim-evolution#426]
I am using the latest release (3.3.6) and am having an issue with my triple input XOR gate, when receiving 1 through each input, that the data bit is a 0 when it should instead be a 1.

Schematic:
![Schematic](https://user-images.githubusercontent.com/55923804/88832292-81d36280-d1c8-11ea-86d5-1cf539594dce.png)

Properties:
![Properties](https://user-images.githubusercontent.com/55923804/88832346-96175f80-d1c8-11ea-8cdb-fec491c4b82b.png)

**Comment by LordDecapo** [comment]
You have the Multiple Input Behavior set to "when one input is on" when for the behavior you are wanting, you need to have it set to "when an odd number are on".
That will give you what you want.

**Comment by maehne** [comment]
@BFH-ktt1: This issue can be closed as resolved.
