### ISSUE TITLE
Oscillation in non-sequential circuits

### ISSUE THREAD

**Issue by jay20162016** [reds-heig/logisim-evolution#432]
In many non-sequential circuits, there is oscillation detected.

**Comment by maehne** [comment]
Could you please provide a Logisim file with a circuit having this issue and describe how to trigger it?

**Comment by BFH-ktt1** [comment]
I close this issue as 1) There is no clear "error"-behavior described and 2) many non-sequential circuits do oscillate, so there would be a bug if we have a circuit that does not oscillate that causes in logisim an oscillation. 
Please be more specific in the description of the issue and please provide an example of a circuit causing an "incorrect" behavior of logisim.
