### ISSUE TITLE
64 Bit Data Bits size?

### ISSUE THREAD

**Issue by eminfedar** [reds-heig/logisim-evolution#435]
Hi, currently there is only **32 Data Bits** support.

Any plans to expand it to **64 bit?**

It would be good for 64 bit CPU, RAM etc. testing... Thanks!

**Comment by jay20162016** [comment]
On the develop branch (if you compile it manually), it is 64-bit.

**Comment by BFH-ktt1** [comment]
Also the latest pre-releases incorporate the 64-bits
