### ISSUE TITLE
False failures

### ISSUE THREAD

**Issue by 0x7C8** [reds-heig/logisim-evolution#437]
I have made a circuit in Logisim and have opened it in Logisim Evolution for a verification.
It seems that testing vector provides false failures when testing a bunch of cases. But when I have tested failed cases separately, they have passed.

Here is a circuit with a test vector files. In 2_3.txt 2 cases fail, meanwhile when testing them separetely (2_3_fails.txt) they pass.

[circuit.zip](https://github.com/reds-heig/logisim-evolution/files/5165663/circuit.zip)

**Comment by BFH-ktt1** [comment]
dear @0x7C8 , I confirm your findings and thank you for the detailed test case. 
I'll put it on my todo list, but with the current covid situation I cannot guarantee a quick response time

**Comment by 0x7C8** [comment]
Upon further analysis, I found out that I made a mistake in my test vector which caused failures. Sorry about that.

**Comment by 0x7C8** [comment]
What caused my confusion is that the test output overwrites expected output value (which is colored red in Test Vector window).
