### ISSUE TITLE
[Linux] Flatpak for Linux

### ISSUE THREAD

**Issue by TheEvilSkeleton** [reds-heig/logisim-evolution#448]
I've created a fully working flatpak for logisim-evolution: https://github.com/TheEvilSkeleton/Logisim-flatpaks.

In short, Flatpak is a universal package manager for Linux. No matter what distribution you use, you can compile Flatpak from source, and have access to the [Flathub](https://flathub.org/) repository.

The flatpak has those advantages:
- it comes with a `.desktop` file. A `.desktop` file is an executable icon that can be found in the application menu, so we do not need to run `java -jar` in the terminal everytime we want to launch it, see [1];
- it is sandboxed:
   - It only has access to the Documents folder;
   - it has no access to internet or audio.

Keep in mind that this is just an initial flatpak. We can restrict or permit more permissions later.

I am not planning on being the only one to maintain the flatpak in Flathub anytime soon, as I do not use logisim-evolution yet, thus it will not be published in Flathub until other people are willing to maintain it with me. My schoolmates have had problems running logisim-evolution in Windows and macOS, so it isn't a piece of software we can use over Logisim unfortunately.

---

Related to https://github.com/reds-heig/logisim-evolution/issues/321#issuecomment-579730874 https://github.com/reds-heig/logisim-evolution/issues/439#issuecomment-688159436

---

[1] 
![image](https://user-images.githubusercontent.com/50847364/99324477-54c3c200-2842-11eb-8d1d-1c9e9ee26450.png)

**Comment by BFH-ktt1** [comment]
Thanks a lot for your work. I will look into the details the moment my current packed schedule shows some room.

**Comment by TheEvilSkeleton** [comment]
I completely forgot to update: I started using it. I used the flatpak for a whole day and it seems to be working just fine.

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 so in https://github.com/TheEvilSkeleton/Logisim-flatpaks/commit/c8baa8ccc0563510624904b4e13484de90d28fec, I made it show up in the "Open with" dialog:

![image](https://user-images.githubusercontent.com/50847364/100296174-87b03900-2f59-11eb-9934-5bf98beb2f1f.png)

The problem is that when the file name has a space, e.g. `~/Documents/Logisim/Logisim test.circ`, or the previous folder's name has a space, e.g. `~/Documents/Logisim test/Logisim.circ`, the file won't launch at all. I'm pretty sure it's an upstream issue, because I can launch it successfully when there is no space.

**Comment by TheEvilSkeleton** [comment]
> Thanks a lot for your work. I will look into the details the moment my current packed schedule shows some room.

I wouldn't mind being one of the maintainers when it gets published in Flathub. Just that I'd like to collaborate with others so I don't have to do 100% of the work.

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , Concerning the spaces; this is a general problem a lot of unix-based software has, as in unix the space is used for separation between the program and it's argument(s). So in general it is a bad idea to use spaces in either the file-name or the directory name. If those spaces are used, for example in the workspace name, than also the syntehsize and download functionality will give problems. Of course this can be "fixed" by putting the filename in double quotes or by backschlassing the spaces, but this "fix" does not work for the software that is used by logisim to do the external simulation (modelsim/questasim) and/or the synthesis and p&r (Intel Quartus/Xilinx/Vivado). Therefore the best solution is to not use spaces in either filenames or directory names.

Concerning maintaining on flathub, thanks for your offer, and no, you will not be alone.

**Comment by TheEvilSkeleton** [comment]
> Concerning maintaining on flathub, thanks for your offer, and no, you will not be alone.

Awesome. I'm going to submit an MR soon in Flathub.

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 https://github.com/flathub/flathub/pull/1951

**Comment by TheEvilSkeleton** [comment]
> but this "fix" does not work for the software that is used by logisim to do the external simulation (modelsim/questasim) and/or the synthesis and p&r (Intel Quartus/Xilinx/Vivado). Therefore the best solution is to not use spaces in either filenames or directory names.

That's understandable, but also problematic, as the program doesn't support this basic feature. People will often think that the flatpak will broken when opening a file containing a space, when in reality it's an upstream issue.

I'm able to open files that have spaces from the program itself, but from the "Open With" dialog I cannot.

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , sorry for not being there for a longer time, but the last weeks of the semester are "killing" me. Will look in the open issues from next week on. Thanks for all your work.

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 don't worry, take your time, and I'm glad to help. I closed this issue because it is resolved.

Here's a recap if you were out of touch with what has happened:

- logisim-evolution is now available in the Flathub repository: https://flathub.org/apps/details/com.github.reds.LogisimEvolution, so it will show in GUI software centers like GNOME Software[1].
- The repository for the package is here: https://github.com/flathub/com.github.reds.LogisimEvolution. You should have an invitation to maintain the repository.
- I added some stuff like "Open with Logisim Evolution" to make opening `.circ` files easier[2].
- An icon should appear in your application launcher[3] (but will prefer to use an official icon).

[1]
![image](https://user-images.githubusercontent.com/50847364/102096210-7177f900-3df2-11eb-8e9e-8f4693e9b0c5.png)
[2]
![image](https://user-images.githubusercontent.com/50847364/102096662-f531e580-3df2-11eb-8203-0bf7572fded5.png)
[3]
![image](https://user-images.githubusercontent.com/50847364/102096967-4c37ba80-3df3-11eb-8cac-7b58de345c02.png)

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , I seem to remember that there was still a question open concerning flatpack files that should be "moved" to the logisim tree. I seem have lost this email, could you give me a pointer to the issue? Thanks in advance. I plan to make a V3.4.0 (which is the current development tree with some bug fixes) in the coming days.

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 https://github.com/flathub/flathub/pull/1951#discussion_r533142094, and https://github.com/flathub/flathub/pull/1951#discussion_r533142138.

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , I added the files in the logisim repository, and build a new stable version. It would be nice to have a small README on how to update flatpak wenn there is a new release, I'm completely new in building flatpak applications, so could you enlighten me?

**Comment by TheEvilSkeleton** [comment]
@BFH-ktt1 it's really easy to bump versions. It's also convenient since the [Flathubbot](https://github.com/flathubbot) does the "building" process.

All you have to do is go to the manifest, and change the `url` and `sha256` lines (https://github.com/flathub/com.github.reds.LogisimEvolution/blob/master/com.github.reds.LogisimEvolution.yml#L50-L52); you type the URL you want to fetch, and then you type the hash of what you want to fetch. Once done, you can test if the flatpak works by submitting a merge request in the logisim-evolution repository. If it fails, then Flathubbot will comment it [failed](https://github.com/flathub/flathub/pull/1951#issuecomment-734214923), if it successfully builds, it will comment saying it's [successful](https://github.com/flathub/flathub/pull/1951#issuecomment-735945567).

Since you moved [some files](https://github.com/reds-heig/logisim-evolution/tree/master/support/Flatpak) to upstream, we will need to make the flatpak fetch those files instead of the [root repository](https://github.com/flathub/com.github.reds.LogisimEvolution). You can see the lines for the [`.desktop`](https://github.com/flathub/com.github.reds.LogisimEvolution/blob/master/com.github.reds.LogisimEvolution.yml#L42-43) and [MIME](https://github.com/flathub/com.github.reds.LogisimEvolution/blob/master/com.github.reds.LogisimEvolution.yml#L48-49), just a simple:

(Pardon for incorrect indentation. I'm using my phone right now)

```diff
-   path: com.github.reds.LogisimEvolution.desktop
+  url: URL
+  sha256: HASH
```

`dest-filename` is just renaming the file to something else. Since the [Flatpak directory](https://github.com/reds-heig/logisim-evolution/tree/master/support/Flatpak) has the right name, I don't think we have to rename.

You can give it a try. Just submit an MR in the [com.github.reds.LogisimEvolution](https://github.com/flathub/com.github.reds.LogisimEvolution) repository. I'll request some changes if you ever need some help.
