### ISSUE TITLE
Create a logo for logisim-evolution

### ISSUE THREAD

**Issue by TheEvilSkeleton** [reds-heig/logisim-evolution#449]
As the title suggests.

**Comment by maehne** [comment]
Have you checked out the icons, which are included in the new installer packages created with `gradle jpackage`? If you would like to suggest a new or enhanced logo to distinguish Logisim-evolution from the original Logisim and other forks. Please feel free to make a proposal and pull request!

**Comment by maehne** [comment]
@TheEvilSkeleton: Are you satisfied by the logos used by the new installer packages for the program itself and Logisim circuit files? Can we close this issue or will you provide a PR with a proposal for a new one?

**Comment by TheEvilSkeleton** [comment]
> @TheEvilSkeleton: Are you satisfied by the logos used by the new installer packages for the program itself and Logisim circuit files? Can we close this issue or will you provide a PR with a proposal for a new one?

Can you show me how it looks? I haven't really had the time to check on the logo.

**Comment by maehne** [comment]
@TheEvilSkeleton, it looks like this:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/1174243/106034560-57108b00-60d3-11eb-92a5-4a0d2f465bd1.png">

So, no real difference to the icon of the original Logisim.

**Comment by TheEvilSkeleton** [comment]
I guess we could close the issue since it looks fine. I'd like to come up with a better logo but I don't really have the time.
