### ISSUE TITLE
translation mistake [German]

### ISSUE THREAD

**Issue by slajurk** [reds-heig/logisim-evolution#450]
Hello guys,
I found two translation mistakes. They are located in the file logisim-evolution-3.3.6.zip\logisim-evolution-3.3.6\src\main\resources\resources\logisim\de\std.properties.

This are the two lines:
Line 88 subtractorBorrowOutTip = Leihausgang: ist 1, wenn die Differenz ngativ ist
Line 469 ramConfirmClearMsg = Sind SIe sicher, daß der Speicher auf Null gesetzt werden soll?
Line 614 plexerSelectBottomLeftOption = Unten/Lonks

The corrected lines would be:
Line 88 subtractorBorrowOutTip = Leihausgang: ist 1, wenn die Differenz negativ ist
Line 469 ramConfirmClearMsg = Sind Sie sicher, dass der Speicher auf Null gesetzt werden soll?
Line 614 plexerSelectBottomLeftOption = Unten/Links

See the attached images.
![subtrahierer_negativ](https://user-images.githubusercontent.com/74613374/99501067-8d1aeb80-297b-11eb-8944-31691e6ba2e7.png)
![ram_loeschen](https://user-images.githubusercontent.com/74613374/99502777-da985800-297d-11eb-8b72-779fa5dec024.png)
![multiplexer_untenlinks](https://user-images.githubusercontent.com/74613374/99501069-8e4c1880-297b-11eb-8a68-f144b2eaaa46.png)

**Comment by BFH-ktt1** [comment]
Thanks a lot for your findings. It will be fixeed in the next release.
