### ISSUE TITLE
Beeper component

### ISSUE THREAD

**Issue by zdimension** [reds-heig/logisim-evolution#464]
It would be nice to have a beeper component in the I/O category, similar to the one in Multimedia Logic (allows playing a specific frequency for an exact duration). Since Logisim already provides graphical output (7seg, LEDs, TTY), it would make sense to also provide audio output.

**Comment by BFH-ktt1** [comment]
There is the buzzer component int the "Input/Output Extra" library, does this not suite your needs?

**Comment by zdimension** [comment]
Oh well, I totally forgot about the extra libraries. The buzzer component is exactly what I was looking for. Sorry about that.
