### ISSUE TITLE
Unable to use multiple buzzers simultaneously

### ISSUE THREAD

**Issue by zdimension** [reds-heig/logisim-evolution#470]
When having 2 or more buzzers on at the same time, the sound that gets played is corrupted, as if the two buzzers were trying to write to the same buffer.

**Comment by BFH-ktt1** [comment]
This is a known issue, and related to the implementation of the buzzer component. More than 1 buzzer in a system is not supported for the moment and very low on the list of "things to fix".

**Comment by zdimension** [comment]
Fixed by #519.
