### ISSUE TITLE
Open .circ files with logisim-evolution by default

### ISSUE THREAD

**Issue by mamarguerat** [reds-heig/logisim-evolution#471]
When double-clicking on a .circ file, it would be great if it can open logisim-evolution automatically. The only way today is to open logisim-evolution and then click on file -> open and find the file.

**Comment by BFH-ktt1** [comment]
@mamarguerat , this problem should be solved by the installers (windows, linux, MacOSx) that you find for V3.4.1. Please let me know if the problem persists after installing v3.4.1 using the installers.

**Comment by mamarguerat** [comment]
It's working, thanks
