### ISSUE TITLE
Cannot open logisim-evolution-3.4.1.dmg on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by HongxiaoN** [reds-heig/logisim-evolution#476]
Can not properly open the logisim-evolution-3.4.1.dmg on macOS big Sur 11.1, it always shows that " 'logisim-evolution' is damaged and can't be opened. You should eject the disk image."

**Comment by BFH-ktt1** [comment]
You need to unlock the security requirement on macOS big Sur (see #475)

**Comment by HongxiaoN** [comment]
I fixed it by using tip4 on the web page
https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/. 
Thank u
