### ISSUE TITLE
Tag a release and provide a binary download

### ISSUE THREAD

**Issue by U-D13** [reds-heig/logisim-evolution#48]
This issue stands to propose that 

0. a commit is tagged with the appropriate version number (or, preferably, all release commits are tagged)
0. and [a new release is made][new release] with the binary compiled against it attached.

Currently the only hint on a version number outside of the actual sources is the following line in [README.md][readme]:
```bash
java -jar logisim-evolution-2.13.9.jar
```
and the only source of a binary download is a private IIS7 server which at the moment of this writing is happily 500'ing. I doubt whether all current and potential Logisim users have Java SDK installed as well as they know how to compile from sources to deal with the unavailable binaries on their own.

I personally don't really feel the inclination to pull that untagged `HEAD` of your `master` to have a go at compiling myself, without knowing for sure whether it is a stable release or some WIP, and whether it will compile at all.

By resolving this issue in the proposed way you would achive

0. commit history that is more readable and manageable, as releases are tagged
0. and binary downloads always available for every future (and, optimally, past as well) release.

[readme]: https://github.com/reds-heig/logisim-evolution/blob/2b7bf97a/README.md#how-to-install-logisim-evolution
	"How to install logisim-evolution - logisim-evolution/README.md at 2b7bf97a · reds-heig/logisim-evolution"
[new release]: https://github.com/reds-heig/logisim-evolution/releases/new
	"New release · reds-heig/logisim-evolution"

**Comment by reds-heig** [comment]
I've temporarily added a copy of the jar as a release. This release can be considered stable -- we've used it for the past months with the students and had no major issues.
I will be happy to follow your advices for the releases we plan to do in the next months.
Thanks a lot for your suggestions!
