### ISSUE TITLE
Logic gates graphical bug?

### ISSUE THREAD

**Issue by Von-Braun** [reds-heig/logisim-evolution#486]
For some reason, my gates are appearing in box form, rather than as their respective symbols. Any idea on why this is? My OS is Windows 10 64-bit.
```
> java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```

![21012712031665990266](https://user-images.githubusercontent.com/25232065/106026691-0c3a4780-60c2-11eb-9b7a-f568f95631f7.png)

**Comment by BFH-ktt1** [comment]
@Von-Braun , You have on the settings page selected the IEC-Symbols instead of the ANSI-Symbols. You can change it back by
Window->Preferemces->International->Gate Shape->ANSI

**Comment by Von-Braun** [comment]
@BFH-ktt1 Welp, now I feel like an idiot for spending over an hour on this, haha. Thanks very much!
