### ISSUE TITLE
Hex editor for RAM: unable to edit words wider than 32 bits

### ISSUE THREAD

**Issue by regus-pregus** [reds-heig/logisim-evolution#487]
Software version: 3.4.1
Problem description: when RAM component data bit width parameter is selected to more than 32 bits, hex editor displays enough characters per word to fit specified number of bits (e.g. for 64-bit width it shows 16 hex characters per word, which is correct), however, editing the value truncates at 32 bits (4 bytes).
Repro:
0) Start logisim-evolution version 3.4.1
1) Place RAM component on canvas
2) Specify Data Bit Width = 64 in Properties window
3) Right-click on RAM component on canvas, select Edit Contents... menu item, hex editor will launch
4) Select any cell in hex editor and start entering values. Only first 8 characters will enter correctly, after which new characters will be displacing old characters instead of overflowing to the upper 8 characters. Upper 8 characters (4 bytes) will always remain zero.

**Comment by maehne** [comment]
Thanks @regus-pregus for the bug report! I can reproduce the wrong behaviour. Interesting that it works for the first word, but not the other memory places. It's probably a relatively small cause overlooked, when the maximum bus width was increased from 32 bit to 64 bit. @BFH-ktt1: Can you have a look?

**Comment by maehne** [comment]
@BFH-ktt1: In this [branch](https://github.com/mkayaalp/logisim-evolution/tree/unh-ece562-spring2020) by @mkayaalp might be a part of the solution to fix the issue.

**Comment by BFH-ktt1** [comment]
@regus-pregus : It should be fixed by my latest PR. Please reopen if the problem still persists.
