### ISSUE TITLE
Can't load previously saved circ

### ISSUE THREAD

**Issue by Tobias004** [reds-heig/logisim-evolution#49]
File Attached:
When Adding the custom circuit named "Register" to "main", the .circ does not load. The attached file does not load. 
.circ XML: 
Sorry can't upload file hier so I uploaded it to tinyupload.com:
http://s000.tinyupload.com/index.php?file_id=04318125559728976903

**Comment by reds-kgs** [comment]
Hello,

Did you create the circuit with another version of logisim and then open it with logisim-evolution?

There are some issues with the registers when I open the design:

at com.cburch.logisim.gui.generic.RegTabContent.getAllRegisters(Unknown Source)
at com.cburch.logisim.gui.generic.RegTabContent.fillArray(Unknown Source)
at com.cburch.logisim.gui.generic.RegTabContent.propagationCompleted(Unknown Source)
at com.cburch.logisim.circuit.Simulator.firePropagationCompleted(Unknown Source)
at com.cburch.logisim.circuit.Simulator$PropagationManager.run(Unknown Source)

**Comment by Tobias004** [comment]
Hi,
No, I created the circuit with logisim-eolution only. I don't have the original logisim installed at all.

**Comment by BFH-ktt1** [comment]
Hi Tobias004,
As "Register" is already a standard component of the library memory, you cannot use this name for a sub-circuit. Try to rename in the circ-file "Register" to "Registerfile" and afterwards to open it. It should work.

**Comment by Tobias004** [comment]
Thank you, it works after renaming the circuit "register" to something else.

You should definitely deny circuit Names with the same name as already known circuits!
Maybe auto correction of conflicting name(s) when saving together with a message box?
