### ISSUE TITLE
MSI installer for Logisim-evolution 3.4.2 contains unnecessary files

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#514]
Due probably a not clean build directory, the MSI installer for Logisim-evolution 3.4.2 on Windows does contain unnecessary files, which cause, e.g., the FPGA boards to show up twice in the FPGA Commander. The `app/` directory contains two JAR files and one EXE file, where there should be only a single JAR file:

![Screenshot of app folder](https://user-images.githubusercontent.com/1174243/109999834-efbdaa80-7d12-11eb-844c-adbe0b013e98.png)

The MSI installer should be regenerated. Maybe, the Gradle build scripts could be enhanced to clean first the build directory when generating installers.

**Comment by BFH-ktt1** [comment]
Updated the .msi
