### ISSUE TITLE
64 bit Counter component displays bits twice

### ISSUE THREAD

**Issue by simoc** [reds-heig/logisim-evolution#527]
A 64 bit Counter component displays the lower 32 bits of the value twice.

For example, when the counter has the value 9, the pins 0 and 3 correctly have the value 1, but pins 32 and 35 also have the value 1. See attached screenshot.

![counter64](https://user-images.githubusercontent.com/1910647/111701271-df412000-883a-11eb-977b-710d73b98a2a.png)

I am using the `develop` git branch.

**Comment by maehne** [comment]
This issue can be closed as fixed due to the merge of PR #528.

**Comment by simoc** [comment]
Fixed by #528. I am closing this issue manually.
