### ISSUE TITLE
Base Library Missing

### ISSUE THREAD

**Issue by Wynadorn** [reds-heig/logisim-evolution#542]
In the original Logisim a category called Base is available.
![image](https://user-images.githubusercontent.com/4095127/113822588-e72b1a80-977d-11eb-97fd-8bddcea8c351.png)

This category is necessary for: **Project -> Options -> Toolbar** and **Project -> Options -> Mouse**
Without this section you're unable to bind these tools to keybinds or put them on the toolbar.

**Comment by BFH-ktt1** [comment]
This is intentional. The "Base" tools are default in the Toolbar.
Closing the issue.

**Comment by Wynadorn** [comment]
Sorry, I should have been more detailed about my issue.

I'd like to assign a hot key to these tool buttons. This uses to be able underneath the Mouse tab however because the base tab has (intentionally) been removed I'm no longer able to.

**Comment by BFH-ktt1** [comment]
This makes sense, I will look into the details in due time, however, it may take a while

**Comment by BFH-ktt1** [comment]
This should be fixed in my latest push to develop. Please reopen the issue if it is not resolved. (note it is not yet available in 3.4.5)
