### ISSUE TITLE
Texttool broken in V3.4.4.

### ISSUE THREAD

**Issue by BFH-ktt1** [reds-heig/logisim-evolution#544]
For the moment you cannot save text added to your circuits in V3.4.4.

**Comment by micahwagner** [comment]
This bug still happens for me

**Comment by CuriousMarc** [comment]
Can input Text, but it won't save it ("Text element not found") nor can you copy and paste it ("Library element not found")

**Comment by micahwagner** [comment]
yeah thats what happens for me as well

**Comment by micahwagner** [comment]
Im pretty sure this bug has been tracked and has a known fix

**Comment by BFH-ktt1** [comment]
Fixed in V3.4.5, Closing
