### ISSUE TITLE
Clock broken when used with RAM in 3.4.4

### ISSUE THREAD

**Issue by davidhutchens** [reds-heig/logisim-evolution#545]
If you start a new project, drag a RAM component into it,  attach a clock input to C1, then try to get the clock to run, it fails to do so.

The clock runs in 3.4.3.

**Comment by BFH-ktt1** [comment]
I confirm this bug. There is a null-pointer exception when fetching the data of the component. I'll look into the details as soon as I have a moment. Thanks for the bug-report!

**Comment by BFH-ktt1** [comment]
@davidhutchens , it should be fixed by my latest push in develop. Closing the issue, but please reopen if the bug is not treated correctly.
