### ISSUE TITLE
Project will not simulate unless all probe points are deleted

### ISSUE THREAD

**Issue by CuriousMarc** [reds-heig/logisim-evolution#552]
Here is the same project, one with probe points, one without probe points. The one with probe points will refuse to run. The clock will not start. However, if you delete all the probe points one by one, after you delete the last one, it will run again! If you add them back in one by one, it will keep running too. But if you save the project with the monitors and open it again, it will not run. Removing all the probe points will get it to run again. Using 3.4.4. Thanks!
Marc

(BTW I was using the probe points as alternate to labeling the lines, since the text labels do not work either, they will not save with your project)

[Probe Points Bug.zip](https://github.com/reds-heig/logisim-evolution/files/6371215/Probe.Points.Bug.zip)

**Comment by BFH-ktt1** [comment]
Thank you very much for your bug report. This has been fixed in my latest push in the development branch. Closing the issue for now, please reopen if it does not work for you.

**Comment by CuriousMarc** [comment]
Wow that was quick! 

Are you also working on a text label fix? That’s really what I was trying to get around by putting all my little monitors – all I wanted is a way to label the wires...

Thanks for the amazing work.

Marc

**Comment by BFH-ktt1** [comment]
Also the text-bug has already a work-around in head of development, hope this helps.
