### ISSUE TITLE
Missing Application Icon (OS X)

### ISSUE THREAD

**Issue by MosheBerman** [reds-heig/logisim-evolution#57]
When running logisim-evolution on OS X via command line, the app icon is simply the Java icon. Is there an application icon on other platforms? If not, I'm happy to re-create the original Logisim one, or do a new one in Photoshop.

**Comment by reds-heig** [comment]
There are some icons in resources/logisim/img, but on my Linux machine no icon is set.
It would be great to have a new one! :)

**Comment by BFH-ktt1** [comment]
Can this issue be closed?

**Comment by maehne** [comment]
Yes, this can be closed, as PR #115 has been merged for a long time.
