### ISSUE TITLE
Erro Mux with open input

### ISSUE THREAD

**Issue by etienne-messerli** [reds-heig/logisim-evolution#75]
When we use a Mux 4 to 1 (2 inputs for selection) and we leave 1 or 2 input open (not connected). The simulation is running correctly as long as the selection select connected input. But we get a error during the integration (FPGA Commander).

Desired correction: make the both response (simulation and integration) identical. I will prefer that both give a error (input open)

**Comment by BFH-ktt1** [comment]
I tried to reproduce your findings with your block "Bloc_Multiplexer" which has two inputs open.
Going to the FPGACommander will synthesize and download without an error message.
Logisim does not produce an error, it will just leave the line "floating". The corresponding behavior on the FPGA will be a '0' in case of an unconnected mux-input.
Could you be more precise in exactly what is in your view incorrect?
