### ISSUE TITLE
Menu bar in memory data loading is deceptive

### ISSUE THREAD

**Issue by robertorigamonti** [reds-heig/logisim-evolution#81]
When loading a .raw file in a memory component, the normal procedure is to right-click on the component and click on "Load image...".
However, if the memory content is displayed, the "open" command present in the "file" menu is the open command of a .circ file, and this of course fails to load the desired content in the component.
Since the menu bar is not needed there, an idea to avoid the confusion could be to get rid of the menu bar entirely.

**Comment by BFH-ktt1** [comment]
Fixed in my latest push.
