### ISSUE TITLE
RAM with Low Level trigger works exactly same as High Level

### ISSUE THREAD

**Issue by disaderp** [reds-heig/logisim-evolution#85]
#86 
1. I am not sure about that, but I think that if one RAM works as asynchronous RAM with inverted inputs and the second with not inverted, those two circuits should be identical.

![image](https://cloud.githubusercontent.com/assets/3391417/14672337/6d4b61f0-06f7-11e6-9575-2119f5524487.png)

However the first with inverted inputs(Low Level) works same as High Level (below), and gives error because there are two inputs connected together(from RAM and from tristate buffers)

2. [Another issue concerning RAM module is the fact that after an upgrade (from original to evolution version) the Library Reference does not match the new component in many cases.

3. Also Trigger mode is not well documented and it took me really awhile to understand that LowLevel and HighLevel are actually asynchronous modules as opposed to Rising and Falling Egde. It is quite confusing and it would be also cool if RAM had also different properties like Mode where someone could choose whether wants to use Synch module or Async

@ Edit: The pull request fixes the first issue

**Comment by alexandremalki** [comment]
Hi disaderp,
Thank you for the update, I tested it and indeed there is problem. I will try to test your modification and merge it if everything is fine in our main branch.

Have a nice day.
