### ISSUE TITLE
Tunnel labels lost during copy/paste

### ISSUE THREAD

**Issue by DanHarty** [reds-heig/logisim-evolution#87]
Tunnels lose their label when they are copy/pasted. They retain all other attributes (font, direction, and bit width).

It gets tedious retyping or copy/pasting the label each time. I assume this is unintended behavior? It's probably because all other labels need to be unique due to HDL so they aren't copied. Tunnel labels are obviously non-unique and it would be quite useful to copy them.

EDIT: Probably related, I occasionally get a name collision error when moving a tunnel with a non-unique label.

**Comment by roy77** [comment]
In my current project I need many connected tunnels and therefore have the same name/label. But with copy/paste the name/label is lost.

For a better behavior I disable the clearing of the label for class tunnel.

6d7ddbb

A better solution could be a class member which hold information about clearing.

**Comment by alexandremalki** [comment]
Hi roy77,
Thank you for your help, indeed that was very annoying to write again and again the label each time you copy them (and by nature you need at least two with the same name).

We will investigate on how to make it cleaner.

**Comment by BFH-ktt1** [comment]
This issue should have been solved in the two main branches. Closing the issue.
