### ISSUE TITLE
Book link is broken

### ISSUE THREAD

**Issue by jvalleroy** [reds-heig/logisim-evolution#96]
In README.md:
"Another good reference is this book, where basic electronics is explained with the help of Logisim."

The link goes to http://www.lulu.com/shop/george-self/exploring-digital-logic-with-logisim-ebook/ebook/product-21118223.html, which says "can't find this product".

**Comment by maehne** [comment]
This seems to be the correct link to the paperback edition: http://www.lulu.com/shop/george-self/exploring-digital-logic/paperback/product-22747579.html
An e-book version doesn't seem to exist anymore.

**Comment by egrath** [comment]
The Book and the accompanying Lab Manual are released under the Terms of "CC BY 3.0" License, so it should be allowed to share them according to it. Eventually this project should host them here for anyone interested; I wrote the author to get a copy of them for my own purposes and have them available when needed.

**Comment by georgeself** [comment]
I'm working on a completely new book with enhanced labs and better descriptions. I expect that to be complete by about July 1, 2018. I'll post a link here when it's done.

**Comment by grself** [comment]
I just now noticed this discussion -- sorry about the long lag time. Here are my Github links for the digital logic book and accompanying lab manual:

[Digital Logic Text](https://github.com/grself/CIS221_Text)
[Logisim-evolution Lab Manual](https://github.com/grself/CIS221_Lab_Manual)

I'm updating both for the upcoming fall term (2019) but they should be available at my Github repository as I make changes.

**Comment by BFH-ktt1** [comment]
Should be fixed, closing issue
