### ISSUE TITLE
Auto-update at startup renders program unresponsive

### ISSUE THREAD

**Issue by wildptr** [reds-heig/logisim-evolution#97]
When the program is launched for the first time after `ant run`, no GUI shows up after a long time, and there's not even a single message from the terminal that tells the user what's happening, making the program totally unusable. Removing auto-update logic from startup code resolves the issue. Consider disabling auto-update by default?

**Comment by BFH-ktt1** [comment]
We will consider a window pup-up to indicate the user that logisim-evolution is querying for a possible update. to disable the update feature you can start logisim-evolution with the command-line option -noupdates
Hope this resolves the problem.
