### ISSUE TITLE
Better SVG curve support

### ISSUE THREAD

**Issue by peterb12** [reds-heig/logisim-evolution#99]
SvgReader.java only supports the "M" and "Q" path directives in bezier curves. Consequently, even if one crafts a path for an appearance in some other program, logisim-evolution is not capable of reading it.  It would be good if we could use arbitrary SVG for apperances, rather than a subset.

**Comment by peterb12** [comment]
Put another way: the file format is incapable of representing the images for the built-in components in std/gates/PainterDin.java and PainterShaped.java.  It should be extended such that it can.

**Comment by BFH-ktt1** [comment]
SVG export is now available for all parts of logisim (development branch).
Hope this solves this issue
